animal = input("What is your favorite animal? ")
building = input("Name a famous building: ")
color = input("What is your favorite color? ")
print("\nHickory Dickory Dock!")
print("The " + color + " " + animal + " ran up the " + building + ".")